- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: db.niksantechnologies.com
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        instance_type: t2.micro
        name: " {{ item }}"
        security_group: allow-everything
        image_id: ami-090252cbe067a9e58
        tags:
          Name: "{{ item }}"
      loop:
        - db
        - backend
        - frontend
      register: ec2_instances_info
- name: print output
  ansible.builtin.debug:
    msg: "Output: "{{ e2_instances_info }}""
