- name: configure db server
  hosts: db
  become: yes
  vars_files:
    - credentials.yaml
  roles:
    - db

- name: configure backend server
  hosts: app
  become: yes
  roles:
    - backend

- name: configure frontend server
  hosts: web
  become: yes
  roles:
    - frontend
