- name: configure db server
  hosts: db
  vars_files:
    - credentials.yaml
  become: yes
  roles:
    - db

- name: configure backend server
  hosts: app
  vars_files:
    - credentials.yaml
  become: yes
  roles:
    - backend
# - name: configure frontend server
#   hosts: web
#   become: yes
#   roles:
#     - frontend
